export const namelField = '#name'
export const emailField = '#email'
export const telpField = '#phone'
export const passwordField = '#password'
export const confirmpasswordField = '#passwordConfirm'
export const signinBtn = '#registerForm > div.my-5 > button'